// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Click struct {
	ID        int64              `json:"id"`
	UrlID     int64              `json:"url_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UserAgent pgtype.Text        `json:"user_agent"`
	IpAddress *netip.Addr        `json:"ip_address"`
}

type Url struct {
	ID          int64              `json:"id"`
	OriginalUrl string             `json:"original_url"`
	ShortCode   pgtype.Text        `json:"short_code"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
