// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Inserts a new click record for analytics.
	CreateClick(ctx context.Context, arg CreateClickParams) error
	// Inserts a new URL record with the original URL.
	CreateURL(ctx context.Context, originalUrl string) (Url, error)
	// Aggregates click counts for a given URL ID over a specified time period (e.g., 'day', 'month').
	GetClicksByPeriod(ctx context.Context, arg GetClicksByPeriodParams) ([]GetClicksByPeriodRow, error)
	// Aggregates click counts grouped by both a time period AND User-Agent.
	GetClicksByPeriodAndUserAgent(ctx context.Context, arg GetClicksByPeriodAndUserAgentParams) ([]GetClicksByPeriodAndUserAgentRow, error)
	// Retrieves all click records for a given URL, ordered by the most recent.
	GetClicksByURLID(ctx context.Context, urlID int64) ([]Click, error)
	// Aggregates click counts for a given URL ID, grouped by User-Agent.
	GetClicksByUserAgent(ctx context.Context, urlID int64) ([]GetClicksByUserAgentRow, error)
	// Retrieves a URL record by its unique short code.
	GetURLByShortCode(ctx context.Context, shortCode pgtype.Text) (Url, error)
	// Updates a URL record with its generated short code.
	UpdateURLShortCode(ctx context.Context, arg UpdateURLShortCodeParams) error
}

var _ Querier = (*Queries)(nil)
